export default {
  theme: {
    extend: {
      colors: {
        brand: 'var(--color-brand)',
        'brand-strong': 'var(--color-brand-strong)',
        'brand-soft': 'var(--color-brand-soft)',
        ring: 'var(--color-ring)',
        surface: 'var(--color-surface)',
        'surface-soft': 'var(--color-surface-soft)',
        'surface-deep': 'var(--color-surface-deep)',
        canvas: 'var(--color-canvas)',
        tint: 'var(--color-tint)',
        accent: 'var(--color-accent)',
        panel: 'var(--color-panel)',
        chip: 'var(--color-chip)',
        contrast: 'var(--color-contrast)',
        border: 'var(--color-border)',
        'border-soft': 'var(--color-border-soft)',
        'border-strong': 'var(--color-border-strong)',
        divider: 'var(--color-divider)',
        text: 'var(--color-text)',
        'text-soft': 'var(--color-text-soft)',
        muted: 'var(--color-muted)',
        label: 'var(--color-label)',
        placeholder: 'var(--color-placeholder)',
        overlay: 'var(--color-overlay)',
      },
      boxShadow: {
        shell: 'var(--shadow-shell)',
        popover: 'var(--shadow-popover)',
        card: 'var(--shadow-card)',
        'card-hover': 'var(--shadow-card-hover)',
        input: 'var(--shadow-input)',
        modal: 'var(--shadow-modal)',
      },
    },
  },
};
