-- ---------------------------------------------------------
-- Table: profiles
-- ---------------------------------------------------------
create table if not exists profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  user_email text unique not null
);

-- ---------------------------------------------------------
-- Table: wines
-- ---------------------------------------------------------
create table if not exists wines (
  wine_id bigint primary key,

  name text not null,
  winery text,
  year integer,
  region_display text,
  image_url text,

  acidity numeric,
  fizziness numeric,
  tannin numeric,
  intensity numeric,
  sweetness numeric,

  grapes text[],
  food_pairings text[],
  flavor_jsonb jsonb,
  price numeric
);
-- ---------------------------------------------------------
-- Table: tasting_notes
-- ---------------------------------------------------------
create table if not exists tasting_notes (
  id bigint generated by default as identity primary key,

  user_id uuid references auth.users(id) on delete cascade,
  wine_id bigint references wines(wine_id) on delete set null,
  price numeric,

  user_acidity numeric,
  user_fizziness numeric,
  user_intensity numeric,
  user_sweetness numeric,
  user_tannin numeric,

  user_flavor jsonb,

  comment text,

  created_at timestamp default now()
);
-- ---------------------------------------------------------
-- Table: taste_tags
-- ---------------------------------------------------------
create table taste_tags (
  id bigint generated by default as identity primary key,
  group_name text not null,
  tag_name text not null,
  unique (group_name, tag_name)
);